language: generic
before_script:
- openssl aes-256-cbc -v -K $encrypted_386dc5387b95_key -iv $encrypted_386dc5387b95_iv
  -in .travis_key.enc -out travis_key -d
- npm install markdown-include
branches:
  except:
  - "/^[0-9]+\\.[0-9]+\\.[0-9]+/"
script:
- "./build/build.js"
- "./build/travis.sh"
